#!/bin/bash
set -e

HUTU=$1
PORT=$2
IMAGE=$3

if [[ -z "$HUTU" || -z "$PORT" || -z "$IMAGE" ]]; then
  echo "Usage: $(basename $0) HUTUSER SSHPORT IMAGE"
  exit 65 # E_BADARGS
fi

if ! getent passwd $HUTU > /dev/null; then
  echo "No user '$HUTU'"
  exit 65 # E_BADARGS
fi

docker run -d --restart=always \
    -p $PORT:22 \
    --name $HUTU-hut \
    -e HOSTNAME=$HUTU-hut \
    -v /home/$HUTU/huthome:/home/$HUTU \
    -v /home/$HUTU/hutetc:/etc/hut \
    $IMAGE 

echo $0 done.

