#!/usr/bin/python -t3
from __future__ import print_function, division, unicode_literals

import os, sys, subprocess, pwd

if len(sys.argv) > 1:
  args = sys.argv[1:]
else:
  args = ["/usr/sbin/sshd", "-D"]
  (home, subdirs, _) = os.walk('/home').next()
  for username in subdirs:
    f = os.stat(os.path.join(home, username))
    try:
      owner = pwd.getpwuid(f.st_uid)
      if owner.pw_name != username:
        msg = "User ID {0} named {1} in hut and not {2} as in host."
        raise RuntimeError(msg.format(f.st_uid, owner.pw_name, username))
    except KeyError:
      subprocess.call(["useradd", "--no-create-home",
                                  "--uid", str(f.st_uid),
                                  username])
      subprocess.call(["groupadd", "--gid", str(f.st_gid), username])

os.execvp(args[0], args)

