#!/usr/bin/python -t3
import os, sys, subprocess, pwd

if (len(sys.argv) < 2):
  sys.exit("Usage: " + sys.argv[0] + " cmd [args...]")

(home, subdirs, _) = os.walk('/home').next()
for username in subdirs:
  # get user/group ID assigned to home directory, setup user if needed
  fs = os.stat(os.path.join(home, username))
  try:
    owner = pwd.getpwuid(fs.st_uid)
    if owner.pw_name != username:
      msg = "User ID {0} named {1} in container and not {2} as in host."
      raise RuntimeError(msg.format(fs.st_uid, owner.pw_name, username))
  except KeyError:
    # no user for UID fs.st_uid so create one
    subprocess.call(["groupadd", "--gid", str(fs.st_gid), username])
    subprocess.call(["useradd", "--no-create-home",
                                "--uid", str(fs.st_uid),
                                "--gid", str(fs.st_gid),
                                username])

cmdline = sys.argv[1:]
os.execvp(cmdline[0], cmdline)

