#!/usr/bin/python -t3

import os, sys, subprocess, pwd

(home, subdirs, _) = os.walk('/home').next()
for username in subdirs:
  f = os.stat(os.path.join(home, username))
  try:
    owner = pwd.getpwuid(f.st_uid)
    if owner.pw_name != username:
      msg = "User ID {0} named {1} in hut and not {2} as in host."
      raise RuntimeError(msg.format(f.st_uid, owner.pw_name, username))
  except KeyError:
    subprocess.call(["useradd", "--no-create-home",
                                "--uid", str(f.st_uid),
                                username])
    subprocess.call(["groupadd", "--gid", str(f.st_gid), username])

args = sys.argv[1:]
os.execvp(args[0], args)

